[package]
name = "ferrum"
version = "0.1.0"
authors = ["m0x"]
edition = "2021"

[dependencies]
bitflags = "2.1.0"
clap = "4.2.3"
env_logger = "0.10.0"
lazy_static = "1.4.0"
log = "0.4.17"
num_enum = "0.6.1"
